### ISSUE TITLE
SCAMMER

### ISSUE THREAD

**Issue by Balmoth** [Fillmore3000/fillmore-dropshipping-starter#2]
Be careful with anything from this creator. I have zero trust in him

DOESN't PAY WHAT HE AGREES ON FOR WORK DONE FOR HIM. DON´T TRUST THIS GUY

**Comment by Fillmore3000** [comment]
No I'm not a scammer - work wasn't delivered plus you was counter productive to the team - all you want is money but provide no value. !!!

**Comment by Balmoth** [comment]
Work was all provided as requested. project was never concluded becuae of your decisions of stopping it. And yes I want my money of the work done and agreed by you that is how the world works mate. But hey want proofs?

https://imgur.com/a/8kcSKrk

A real shame because the project had potential. 
Also what team? You blocked us all

**Comment by Fillmore3000** [comment]
I blocked you all - because and mare con conspired against the project. I
wasn't satisfied with the work. Now that your trying accuse me of being
scammer. It my project and I'm not statised with what you did. That's all
get over it and move on starchildz will still continue just not with the
likes of you and mare.

If you want ill delete the work you provided as it has no value.

If you continue with this action good luck to.

**Comment by Balmoth** [comment]
Don't worry I know you will never pay so yeah all my work was removed already. You fail to fufill your side so you get nothing. And funny how for 2 months when asked if all was ok you always said you were happy with the work yet the second you are accused of not paying nothing was good.

btw no idea what relation is with you and Mare but that is your personal problem. The only connection I have with her was having a look at her discord and giving her some advice in some activities and games for it. But hey want to go tinfoil hat on the world as an excuse be my guest.

Luckily I wasn't dependent on the cash from this for my survival but yeah it still hurts the time wasted not being payed as agreed on (and confirmed several times the last one in end of May) . And just had another project that I help sold out. Kumite. From heromaker studios so hey feel free to check what you missed.

**Comment by Fillmore3000** [comment]
Ok well, if you deleted all that you did. Then you know It wasn't being
used so why try call me a scammer lol. Two the reason I bring mare up to
you. Is because I introduced her to you to help on my project not hers. So
your ok working for free for her but not me lol.
I'm glad the other project did well and good luck in the future. My last
contract was with Apple lol ever heard them so I'll be ok. That's the
reason I blocked you, I'm not slow so next time be loyal peace
